config/routes.rb
Colchonet::Application.routes.draw do
  resources :rooms do
    resources :reviews, only: [:create, :update], module: :rooms
  end
  resources :users

  resource :confirmation, only: [:show]
  resource :user_sessions, only: [:create, :new, :destroy]

  root 'home#index'
end

app/models/review.rb
class Review < ActiveRecord::Base
  POINTS = (1..5).to_a
  belongs_to :user
  belongs_to :room, counter_cache: true

  validates_uniqueness_of :user_id, scope: :room_id
  validates_presence_of :points, :user_id, :room_id
  validates_inclusion_of :points, in: POINTS
end

app/models/room.rb
class Room < ActiveRecord::Base
  scope :most_recent, -> { order('created_at DESC') }

  has_many :reviews, dependent: :destroy

  belongs_to :user

  def complete_name
    "#{title}, #{location}"
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :rooms, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :reviewed_rooms, through: :reviews, source: :room

  scope :confirmed, -> { where.not(confirmed_at: nil) }
  EMAIL_REGEXP = /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/
  validates_presence_of :email, :full_name, :location
  validates_length_of :bio, minimum: 30, allow_blank: false
  validates_uniqueness_of :email
  has_secure_password

  validate do
    errors.add(:email, :invalid) unless email.match(EMAIL_REGEXP)
  end

  before_create do |user|
    user.confirmation_token = SecureRandom.urlsafe_base64
  end

  def confirm!
    return if confirmed?
    self.confirmed_at = Time.current
    self.confirmation_token = ''
    save!
  end

  def confirmed?
    confirmed_at.present?
  end

  def self.authenticate(email, password)
    user = confirmed.find_by(email: email).try(:authenticate,password)
  end
end

app/models/user_session.rb
class UserSession
  include ActiveModel::Model
  attr_accessor :email, :password
  validates_presence_of :email, :password

  def initialize(session, attributes={})
    @session = session
    @email = attributes[:email]
    @password = attributes[:password]
  end

  def authenticate!
    user = User.authenticate(@email, @password)
    if user.present?
      store(user)
    else
      errors.add(:base, :invalid_login)
      false
    end
  end

  def store(user)
    @session[:user_id] = user.id
  end

  def current_user
    User.find(@session[:user_id])
  end

  def user_signed_in?
    @session[:user_id].present?
  end

  def destroy
    @session[:user_id] = nil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  delegate :current_user, :user_signed_in?, to: :user_session
  helper_method :current_user, :user_signed_in?
  def user_session
    UserSession.new(session)
  end
  def require_authentication
    unless user_signed_in?
      redirect_to new_user_sessions_path,
                  alert: t('flash.alert.needs_login')
    end
  end
  def require_no_authentication
    if user_signed_in?
      redirect_to root_path,
                  notice: t('flash.notice.already_logged_in')
    end
  end
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < ApplicationController
  def show
    user = User.find_by(confirmation_token: params[:token])
    if user.present?
      user.confirm!
      redirect_to user, notice: I18n.t('confirmations.success')
    else
      redirect_to root_path
    end
   end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @rooms = Room.take(3);
  end
end

app/controllers/rooms/reviews_controller.rb
class Rooms::ReviewsController < ApplicationController
  before_action :require_authentication
  def create
    review = room.reviews.find_or_initialize_by(user_id: current_user.id)
    review.update!(review_params)
    # retorna status 201 created
    head :ok
  end

  def update
    create
  end

  # variavel privada room eh inicializada pelo parametro room_id
  private
  def room
    @room ||= Room.find(params[:room_id])
  end

  def review_params
    params.require(:review).permit(:points)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :require_authentication, only: [:new, :edit, :create, :update, :destroy]

  def index
    @rooms = Room.most_recent.map do |room|
      RoomPresenter.new(room, self, false)
    end
  end

  def show
    room_model = Room.find(params[:id])
    @room = RoomPresenter.new(room_model, self)
  end

  def new
    @room = Room.new
  end

  def edit
    @room = Room.find(params[:id])
  end

  def create
    @room = Room.new(room_params)
    @room.user = current_user
    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    @room = current_user.rooms.find(params[:id])
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
    end
  end

  private
  # Never trust parameters from the scary internet, only allow the white list through.
  def room_params
    params.require(:room).permit(:title, :location, :description)
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_action :require_no_authentication, only: [:new, :create]
  before_action :require_authentication, only: :destroy

  def new
    @user_session = UserSession.new(session)
  end

  def create
    @user_session = UserSession.new(session, params[:user_session])
    if @user_session.authenticate!
    # Não esqueça de adicionar a chave no i18n!
      redirect_to root_path, notice: t('flash.notice.signed_in')
    else
      render :new
    end
  end

  def destroy
    #esse user_session e o que foi disponibilizado pelo applicationcontroller
    user_session.destroy
    redirect_to root_path, notice: t('flash.notice.signed_out')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_no_authentication, only: [:new, :create]
  before_action :can_change, only: [:edit, :update]

  def index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      Signup.confirm_email(@user).deliver
      redirect_to @user, notice: 'Cadastro criado com sucesso'
    else
      render action: :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user, notice: 'Cadastro atualizado com sucesso'
    else
      render action: :edit
    end
  end

  def can_change
    unless user_signed_in? && current_user == user
      redirect_to user_path(params[:id])
    end
  end

  def user
    @user ||= User.find(params[:id])
  end

  private def user_params
    params.require(:user).permit(:email, :full_name, :location, :password, :password_confirmation, :bio)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def error_tag(model, attribute)
    if model.errors.has_key? attribute
      content_tag(
          :div,
          model.errors[attribute].first,
          class: 'error_message'
      )
    end
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
  def belongs_to_user(room)
    user_signed_in? && room.user == current_user
  end

  def initializeReview(room)
    if user_signed_in?
      user_review = room.reviews.find_or_initialize_by(user_id: current_user.id)
    end
  end
end

app/views/home/index.html.erb
<p>
  <%= t '.text' %>:
</p>

app/views/layouts/_user_navbar.html.erb
<nav>
  <ul>
    <li><%= link_to t('layout.new_room'), new_room_path %> </li>
    <li><%= link_to t('layout.rooms'), rooms_path %> </li>
    <li>
      <%= link_to t('layout.my_profile'),
                  user_path(current_user) %>
    </li>
    <li>
      <%= link_to t('layout.signout'), user_sessions_path,
                  method: :delete %>
    </li>
  </ul>
</nav>

app/views/layouts/_visitor_navbar.html.erb
<nav>
  <ul>
    <li><%= link_to t('layout.rooms'), rooms_path %> </li>
    <li><%= link_to t('layout.signup'), new_user_path %> </li>
    <li><%= link_to t('layout.signin'), new_user_sessions_path %> </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
      <title>Colcho.net</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <div id="header-wrap">
    <h1><%= link_to "colcho.net", root_path %> </h1>
    <% if user_signed_in? %>
        <%= render 'layouts/user_navbar' %>
    <% else %>
        <%= render 'layouts/visitor_navbar' %>
    <% end %>
  </div>
</header>

<div id="content">
  <% if notice.present? %>
      <p id="notice"><%= notice %> </p>
  <% end %>
  <% if alert.present? %>
      <p id="alert"><%= alert %> </p>
  <% end %>
  <%= yield %>
</div>

</body>
</html>

app/views/rooms/_form.html.erb
<%= form_for(@room) do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% @room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rooms/_review.html.erb
<section class="review">
  <% if @room.show_form? %>
      <%= render partial: 'review_form', locals: {room: @room} %>
  <% end %>
</section>

app/views/rooms/_review_form.html.erb
<% if room.can_review? %>
    <%= form_for room.review_route, remote: true do |f| %>
        <% room.review_points.each do |point| %>
            <%= f.radio_button :points, point %>
            <%= f.label :points, point, value: point %>
        <% end %>
        <%= f.submit %>
    <% end %>
<% else %>
    <span class="login_required">
<%= t('.login_to_review') %>
</span>
<% end %>

app/views/rooms/_room.html.erb
<article class="room">
  <h2><%= link_to room.title, room.route %> </h2>
  <%= render partial: 'review', locals: {room: room} %>
  <span class="created">
    <%= t '.owner_html', owner: room.user.full_name, when: l(room.created_at, format: :short) %>
  </span>
  <p>
    <span class="location">
        <%= link_to room.location,"https://maps.google.com/?q=#{room.location}", target: :blank %>
    </span>
  </p>
  <p><%= room.description %></p>
  <% if belongs_to_user(room) %>
  <ul>
    <li><%= link_to t('.edit'), edit_room_path(room.route) %> </li>
    <li><%= link_to t('.destroy'), room_path(room.route), method: :delete, data: {confirm: t('dialogs.destroy')}%> </li>
  </ul>
  <% end %>
</article>

app/views/rooms/edit.html.erb
<h1><%= t '.title' %></h1>

<%= render 'form' %>

<%= link_to t('links.show'), @room %> |
<%= link_to t('links.back'), rooms_path %>

app/views/rooms/index.html.erb
<h1><%= t '.title' %> </h1>
<%= render @rooms %>
<%= link_to 'New Room', new_room_path %>

app/views/rooms/new.html.erb
<h1><%= t '.title' %></h1>

<%= render 'form' %>

<%= link_to t('links.back'), rooms_path %>

app/views/rooms/show.html.erb
<p>
  <%= render partial: 'review', object: @user_review %>
</p>
<p>
  <strong>Title:</strong>
  <%= @room.title %>
</p>

<p>
  <strong>Location:</strong>
  <%= @room.location %>
</p>

<p>
  <strong>Description:</strong>
  <%= @room.description %>
</p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>

app/views/signup/confirm_email.html.erb
<h1><%= t '.title' %> </h1>
<p>
  <%= t '.body', full_name: @user.full_name %>
</p>
<p>
  <%= t '.confirm_link_html',
        link: link_to(@confirmation_link, @confirmation_link) %>
</p>
<p>
  <%= t '.thanks_html', link: link_to('Colcho.net', root_url) %>
</p>

app/views/signup/confirm_email.text.erb
<%= t '.title' %>
<%= t '.body', full_name: @user.full_name %>
<%= t '.confirm_link_html', link: @confirmation_link %>
<%= t '.thanks_html', link: root_url %>

app/views/user_sessions/new.html.erb
<h1><%= t '.title' %> </h1>
<% if @user_session.errors.has_key? :base %>
    <div id="error_explanation">
      <%= @user_session.errors[:base].join(', ') %>
    </div>
<% end %>
<%= form_for @user_session do |f| %>
    <p>
      <%= f.label :email %>
      <%= f.text_field :email %>
      <%= error_tag @user_session, :email %>
    </p>
    <p>
      <%= f.label :password %>
      <%= f.password_field :password %>
      <%= error_tag @user_session, :password %>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>
<p><%= link_to t('.sign_up'), new_user_path %> </p>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
    <p>
      <%= f.label :full_name %>
      <%= f.text_field :full_name %>
      <%= error_tag @user, :full_name %>
    </p>
    <p>
      <%= f.label :location %>
      <%= f.text_field :location %>
      <%= error_tag @user, :location %>
    </p>
    <p>
      <%= f.label :email %>
      <%= f.text_field :email %>
      <%= error_tag @user, :email %>
    </p>
    <p>
      <%= f.label :password %>
      <%= f.password_field :password %>
      <%= error_tag @user, :password %>
    </p>
    <p>
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
      <%= error_tag @user, :password_confirmation %>
    </p>
    <p>
      <%= f.label :bio %>
      <%= f.text_area :bio %>
      <%= error_tag @user, :bio %>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/users/edit.html.erb
<h1>Edição</h1>
<%= render "form" %>
<%= link_to 'Voltar', @user %>

app/views/users/index.html.erb
<h1>Index</h1>

app/views/users/new.html.erb
<h1><%= t '.title' %></h1>
<%= render "form" %>
<%= link_to t('links.back'), root_path %>

app/views/users/show.html.erb
<h1>Perfil: <%= @user.full_name %> </h1>
<ul>
  <li>Localização: <%= @user.location %> </li>
  <li>Bio: <%= @user.bio %> </li>
</ul>
<%= link_to 'Editar Perfil', edit_user_path(@user) %>
<%= link_to 'Voltar', new_user_path %>